# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f54f83fe43458e71592f12ff20ecf2b30060a85a2435a6256af5747285e2e39311ce4bd33840c1e96597f8688f42e7079f244803d93b6fe643dcb1e06c90be21

test:
  secret_key_base: f8df5006d432297d4984c822718d772dfe0d110641f8c741618fe7f1b235f612e64433fadffda7fdb11486db51927dcfd4e8915f2f2640573a099aa112e7f89c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
